### ISSUE TITLE
How to use this in arch?

### ISSUE THREAD

**Issue by OrhanYigitDurmaz** [LingmoOS/LingmoDesktop#1]

**Comment by elysia-best** [comment]
Currently an Arch port is being maintained by SIG group @LingmoOS/arch-lingmo-sig. The support for Arch Linux is currently in beta.

**Comment by devLythen** [comment]
Yep, beta now. However, u can try to compile the packages [in this repo](https://github.com/LingmoOS-Testing/lingmo-arch-pkgbuilder) and install all of them. If there's any bug, make an issue plz.

**Comment by OrhanYigitDurmaz** [comment]
Ok thanks

**Comment by elysia-best** [comment]
Mark this as closed. Feel free to reopen this if needed.
